### PR TITLE
Generate XML status report of the last Robocopy run

### PR DESCRIPTION
**Pull request by phil-davis**
and change the emailJobName parameter to jobName.
The user can specify the location and name of the status report file in
parameter statusFile. If not specified, it is written to status.xml in
the same folder as the log file.

### CODE REVIEW

**Comment by phil-davis** [comment]
@individual-it please review. It was very easy to cut-and-paste almost the exact same stuff into robocopy-backup.

**Comment by individual-it** [comment]
I've fixed a bug in the displaying of the deprecated warning
https://github.com/individual-it/Windows-Tools/commit/3afcb98ca8fdabff43fadf8a7f25c8a0ce7c42fe

and also removed the "-" in the XML output as its gives me problems with OCS inventory, so why not to fix the source just now

**Comment by individual-it** [comment]
also check the changing of the date/time format for the XML file
https://github.com/individual-it/Windows-Tools/commit/674e796533220f82abf44c67ed6e268274e5da4c

**Comment by phil-davis** [comment]
I applied the same changes from the hardlink backup just now.

**Comment by individual-it** [comment]
:+1: 
looks fine

**Comment by phil-davis** [comment]
I put that code in the SW share a few days ago. It seems to be running fine - status.xml is now available in the Logs folder on systems that are running this.

**Pull request merged**
