### PR TITLE
Support shadow copy with robocopy

### PR DESCRIPTION
**Pull request by phil-davis**
by creating a sym link to the shadow copy object and using that sym link
for the robocopy command.

### CODE REVIEW

**Comment by phil-davis** [comment]
I will see how this runs overnight and then review again before committing.

**Comment by phil-davis** [comment]
@individual-it This has been running fine the last 2 nights. Can you review and see if there is anything else you can think of that might go wrong with shadow copy here?

**Comment by individual-it** [comment]
```cmd /c```` will give again problems with Win 10
you have just changed all the uses of it to a more compatible way 874f7ec8a4490c252ef91c6cf3df8506f7d36673

**Comment by phil-davis** [comment]
mklink is a built-in of cmd, not a separate command. I tried to use the powershell invoke operator "&" with no joy.
Thanks for the reminder about Windows10 - I will test this on my Windows10 laptop to make sure it works. I expect it will, because these are simple uses of "cmd /c". The problems were differences in the way various parsing of quotes happened when trying to get parameters containing spaces to pass through...

**Comment by individual-it** [comment]
We could also use this library to create links:
https://gallery.technet.microsoft.com/scriptcenter/New-SymLink-60d2531e

**Comment by phil-davis** [comment]
I tried that first. But that nice function uses some .Net class the does not work when trying to make a symlink to a shadow copy \\?\Global\.... path. It gives the error:
Paths that begin with \\?\GlobalRoot are internal to the kernel and should not be opened by managed applications.
I searched about that for a while, and it seemed everyone had this trouble.

**Comment by phil-davis** [comment]
Testing on Windows10 and it ran fine. As long as it is run with admin priv it creates the shadow copy, does the backup, and deletes the shadow copy. Without admin priv it correctly displays warnings that it could not make the shadow copy and then does the normal backup directly from the source disk.

**Comment by individual-it** [comment]
:+1:

**Pull request merged**
